language: python
python:
  - 2.7
  - 3.3
env:
  - DJANGO=django==1.5.4
  - DJANGO=django==1.6
install:
  - pip install $DJANGO
  - python setup.py -q install
script: python test_project/manage.py test require
notifications:
  email: false